server:
  port: 8081
spring:
  application:
    name: user-service
  cloud:
    nacos:
      server-addr: ${newsrec.nacos.server-addr} # 使用配置文件中的地址
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://${newsrec.db.host}:${newsrec.db.port}/${newsrec.db.database}?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${newsrec.db.pw}
mybatis-plus:
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  global-config:
    db-config:
      update-strategy: not_null
      id-type: auto
logging:
  level:
    csu.nr: debug
  pattern:
    dateformat: HH:mm:ss:SSS
  file:
    path: "logs/${spring.application.name}"
knife4j:
  enable: true
  openapi:
    title: 用户服务接口文档
    description: "信息"
    email: yangeureka@163.com
    concat: yang
    #    url: https://www.itcast.cn
    version: v1.0.0
    group:
      default:
        group-name: default
        api-rule: package
        api-rule-resources:
          - csu.nr.user.controller
nr:
  jwt:
    #    location: classpath:newsrec.jks
    location: file:D:\Source\Java\NewsRecommend\backend\nr-gateway\src\main\resources\newsrec.jks
    alias: newsrec
    password: newsrec
    tokenTTL: 30m