version: '3.8'

services:
  nacos:
    restart: on-failure
    image: nacos/nacos-server:v2.2.1
    # 容器名称
    container_name: nacos
    # 端口映射
    ports:
      - 8848:8848
      - 9848:9848
      - 9849:9849
    # 容器权限
    privileged: true
    # 参数设置
    environment:
      JVM_XMS: 128m
      JVM_XMX: 128m
      JVM_MS: 64m
      JVM_MMS: 64m
      MODE: standalone
      NACOS_REPLICAS: 1
      PREFER_HOST_MODE: hostname
    volumes:
      #      - ./nacos/logs:/home/nacos/logs
      #      - ./nacos/plugins:/home/nacos/plugins
      #      - ./nacos/data:/home/nacos/data
      - ./docker/nacos/config/application.properties:/home/nacos/conf/application.properties
    depends_on:
      - mysql
    networks:
      newsrec-net:
        ipv4_address: 172.30.0.3

  mysql:
    container_name: mysql
    image: mysql:8.0.27
    ports:
      - "3306:3306" # 有经验的开发不会直接暴露3306端口
    volumes:
      #      - ./mysql/conf:/etc/mysql/conf.d
      #      - ./mysql/logs:/logs
      #      - ./mysql/data:/var/lib/mysql
      - ./docker/mysql/db:/docker-entrypoint-initdb.d
    command: [
      'mysqld',
      '--innodb-buffer-pool-size=2G',
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci',
      '--default-time-zone=+8:00',
      '--lower-case-table-names=2'
    ]
    environment:
      MYSQL_ROOT_PASSWORD: 123456 #上线修改为复杂密码，否则很容易被黑
    networks:
      - newsrec-net

  nr-gateway:
    restart: on-failure
    build: ./nr-gateway
    # 容器名称
    container_name: nr-gateway
    ports:
      - "8080:8080"
    environment:
      - SPRING_CLOUD_NACOS_SERVER-ADDR=nacos:8848
    depends_on:
      - mysql
      - nacos
    networks:
      - newsrec-net

  user-service:
    restart: on-failure
    build: ./user-service
    # 容器名称
    container_name: user-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - NEWSREC_DB_HOST=mysql
      - NEWSREC_DB_PORT=3306
      - NEWSREC_DB_PW=123456
      - NEWSREC_DB_DATABASE=nr_user
      - SPRING_CLOUD_NACOS_SERVER-ADDR=nacos:8848
    depends_on:
      - mysql
      - nacos
    networks:
      - newsrec-net
   
  news-service:
    restart: on-failure
    build: ./news-service
    # 容器名称
    container_name: news-service
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - NEWSREC_DB_HOST=mysql
      - NEWSREC_DB_PORT=3306
      - NEWSREC_DB_PW=123456
      - NEWSREC_DB_DATABASE=nr_new
      - SPRING_CLOUD_NACOS_SERVER-ADDR=nacos:8848
    depends_on:
      - mysql
      - nacos
    networks:
      - newsrec-net

  operation-service:
    restart: on-failure
    build: ./operation-service
    # 容器名称
    container_name: operation-service
    ports:
      - "8085:8085"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - NEWSREC_DB_HOST=mysql
      - NEWSREC_DB_PORT=3306
      - NEWSREC_DB_PW=123456
      - NEWSREC_DB_DATABASE=nr_operation
      - SPRING_CLOUD_NACOS_SERVER-ADDR=nacos:8848
    depends_on:
      - mysql
      - nacos
    networks:
      - newsrec-net

networks:
  newsrec-net:
    ipam:
      driver: default # 默认的IPAM驱动程序
      config:
        - subnet: 172.30.0.0/16
